services:
        webserver:
                image: webserver
                        build:
            context: ./webserver
            dockerfile: Dockerfile
        hostname: webserver
        ports:
            - "8080:8080"
        container_name: webserver
        links:
            - database
        depends_on:
            - database
    database:
        image: database
        build:
            context: ./database
            dockerfile: Dockerfile
        hostname: database
        ports:
            - "8081:3307"
        container_name: database
        environment:
            MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
            MYSQL_USER_PASSWORD: /run/secrets/mysql_root_password
            MYSQL_USER: user
            MYSQL_DATABASE: db
        secrets:
            - mysql_root_password
            - mysql_user_password
        volumes:
            - ./database/database.sql:/docker-entrypoint-initdb.d/database.sql
secrets:
  mysql_root_password:
    file: ./secrets/mysql_root_password
  mysql_user_password:
    file: ./secrets/mysql_user_password
